// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context TestSyncContext --namespace SqliteWasmBlazor.CryptoSync.Tests --output ../tests/SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.CryptoSync.Tests;

public partial class TestSyncContext
{
    /// <summary>
    /// Admin X25519 private key — for test key derivation. DO NOT use in production.
    /// Static-initializer byte[] (P21 — secret key material exposed to consumers
    /// as bytes, not <see cref="string"/>). The Base64 string literal in this
    /// file's source remains in the compiled assembly metadata; the residual
    /// is acknowledged at codegen layer and out of P21 runtime-API scope.
    /// </summary>
    public static readonly byte[] AdminX25519PrivateKey = System.Convert.FromBase64String("6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=");

    /// <summary>
    /// Admin Ed25519 private key — for test signing. DO NOT use in production.
    /// See <see cref="AdminX25519PrivateKey"/> for the byte[] shape rationale.
    /// </summary>
    public static readonly byte[] AdminEd25519PrivateKey = System.Convert.FromBase64String("0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=");

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("e1d2802f-8877-40d5-bbc9-a121fbea8ed5"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            UpdatedAt = new System.DateTime(639141006109041190L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.PUBLIC,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("498eadbb-8285-4d8b-9854-e8871a09ec23"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639141006109041190L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639141006109041190L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("1c66c13b-8522-4157-a1d9-6f5fa91999ca"),
                GroupContext = "self-e1d2802f887740d5bbc9a121fbea8ed5:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639141006109041190L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639141006109041190L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("95aab62e-1b42-4a64-a05c-c513e2b02fa3"),
                ShareGroupId = System.Guid.Parse("498eadbb-8285-4d8b-9854-e8871a09ec23"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("DcYo+5WlGS1So+2uWNvi9RWE+ROSimdcVDS8eXJ7152vOQW2P3XvyqxTDGaPCDeYGsgn0QIJns/96x50"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("ryoLwPSgB3y/47bNfJ3NlCAdxee9AohC51Bz8by52yKhZdVs8ORXhiK+plBd7jyhZjKfmkoapDr4Y+GcdHlYBg=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("e1d2802f-8877-40d5-bbc9-a121fbea8ed5"),
                UpdatedAt = new System.DateTime(639141006109041190L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("19ceb8a6-eb71-449f-9a0c-fabca6f0091b"),
                ShareGroupId = System.Guid.Parse("1c66c13b-8522-4157-a1d9-6f5fa91999ca"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("361CcFtEi5ECrFNSA5mDAvqqqrtgYobl/BQjXEzRKnot6tcf5VUEWuZcf6Q9HHOys6s8cDJ0jaDmB1/h"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("9v8wXQnssnfIFYq7vo0llpa97wE40gcL/a6zsC3w5BaSEZgYj1lWqKXsj1dWaVcXAKMygJLnIg+xxb8OUyaHDQ=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("e1d2802f-8877-40d5-bbc9-a121fbea8ed5"),
                UpdatedAt = new System.DateTime(639141006109041190L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("bbcc5493-120e-4601-ae34-9e7cc412c97d"),
            ClientGuid = "987a9cf2-fd6c-4e0d-87ab-7bf25fa1ff05",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("e1d2802f-8877-40d5-bbc9-a121fbea8ed5"),
            OwnContactId = System.Guid.Parse("e1d2802f-8877-40d5-bbc9-a121fbea8ed5")
        });

        modelBuilder.Entity<PermissionTableSignature>().HasData(new
        {
            Id = System.Guid.Parse("ece64655-8999-3ed3-a68d-25b617087d86"),
            PermissionHash = System.Convert.FromBase64String("qNdByd08O6MF9RfYhH1p6xzhwxvbS6I9cKmplXlfZYw="),
            AdminSignature = System.Convert.FromBase64String("fy9qhHytYVLlU54y4IaOW7yrpOmbm0kpFyJemNACBzgnGmFPnqf+WgGwkEhUJYan+liPPBihxMQcz5aeTsPDDQ=="),
            AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA="
        });
    }
}