using Microsoft.AspNetCore.Components.Web;
using SqliteWasmBlazor;
using SqliteWasmBlazor.Demo.Models;

namespace SqliteWasmBlazor.Demo.Pages;

public partial class TodoList
{
    /// <summary>
    /// Generated by the <c>[ObservableComponentBatchAsync("listing")]</c>
    /// group on <see cref="TodoListModel"/>: the search term (debounced),
    /// the two mode toggles, and the last completed mutation all arrive
    /// here. This is the only place the table is asked to refetch —
    /// <c>MudTable</c> never reloads on a re-render.
    ///
    /// <para>
    /// <b>No initial DB-stats fill here.</b> Initial population is owned by
    /// the model (<see cref="TodoListModel.OnContextReadyAsync"/> +
    /// <c>OnDbStateChangedAsync</c>) so it stays gated on
    /// <see cref="SqliteWasmBlazor.Crypto.UI.DbStateModel.State"/> = READY — the page partial's
    /// <c>OnContextReady</c> runs at component init regardless of the
    /// encrypted-VFS lock state, which is exactly where the boot-time
    /// SQLITE_NOTADB race used to come from.
    /// </para>
    /// </summary>
    protected override async Task OnListingBatchChangedAsync(CancellationToken cancellationToken)
    {
        if (_table is not { } table)
        {
            return;
        }

        var reload = Interlocked.Increment(ref _reloadCounter);
        SqliteWasmLogger.Trace(LogModule, $"reload#{reload} requested");

        try
        {
            await table.ReloadServerData();
            SqliteWasmLogger.Trace(LogModule, $"reload#{reload} returned");
        }
        catch (OperationCanceledException)
        {
            // A newer change superseded this one; MudTable cancelled the
            // fetch and the page already on screen stays until the next
            // one lands. Caught in the hook, never in the callback.
            SqliteWasmLogger.Trace(LogModule, $"reload#{reload} cancelled");
        }
    }

    private const string LogModule = "TodoPage";

    private static int _reloadCounter;

    private async Task HandleKeyDownAsync(KeyboardEventArgs e)
    {
        if (e.Key == "Enter")
        {
            await Model.AddTodo.ExecuteAsync();
        }
    }
}
