// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context TestSyncContext --namespace SqliteWasmBlazor.CryptoSync.Tests --output SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.CryptoSync.Tests;

public partial class TestSyncContext
{
    /// <summary>
    /// Seeds the admin bootstrap data (TrustedContact, ShareGroup, ShareTarget, DeviceSettings).
    /// Call from <see cref="OnModelCreating"/> after <c>base.OnModelCreating</c> and <c>ConfigureCryptoTables</c>.
    /// </summary>
    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("c95f8926-eabe-4854-9479-cfa2450bfc3a"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            IsTrusted = true,
            UpdatedAt = new System.DateTime(639114047617444130L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(new
        {
            Id = System.Guid.Parse("ed0c3298-f5d1-441a-93ca-421d5b400013"),
            GroupContext = "system:v1",
            KeyVersion = 1,
            AdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            CreatedAt = new System.DateTime(639114047617444130L, System.DateTimeKind.Utc),
            UpdatedAt = new System.DateTime(639114047617444130L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareTarget>().HasData(new
        {
            Id = System.Guid.Parse("e61d54d2-8275-45ba-a134-43925687a184"),
            ShareGroupId = System.Guid.Parse("ed0c3298-f5d1-441a-93ca-421d5b400013"),
            KeyVersion = 1,
            MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            WrappedContentKey = System.Convert.FromBase64String("tJUjswrlsK7vzANSImvRBvXh8qwWUHfuJurdvdz2zLlmwo0O3F9IrxL/rGeEfyEPqPBTt221FStBEn0V"),
            Role = SyncRole.Owner,
            GrantedByContactId = System.Guid.Parse("c95f8926-eabe-4854-9479-cfa2450bfc3a"),
            UpdatedAt = new System.DateTime(639114047617444130L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("2d3cc0f9-2f25-4671-8222-64b441407f45"),
            ClientGuid = "81929cd4-3975-4a90-b968-a58da70da0ea",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("c95f8926-eabe-4854-9479-cfa2450bfc3a")
        });
    }
}