// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context CryptoTestContext --namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync --output SqliteWasmBlazor.TestApp/TestInfrastructure/CryptoSync/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync;

public partial class CryptoTestContext
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    /// <summary>
    /// Seeds the admin bootstrap data (TrustedContact, ShareGroup, ShareTarget, DeviceSettings).
    /// Call from <see cref="OnModelCreating"/> after <c>base.OnModelCreating</c> and <c>ConfigureCryptoTables</c>.
    /// </summary>
    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("ba68902f-58a8-4c9a-b45e-d4123b50caf9"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            IsTrusted = true,
            UpdatedAt = new System.DateTime(639114135398800440L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(new
        {
            Id = System.Guid.Parse("c2ed4793-f258-425a-bcf1-f9b24335982b"),
            GroupContext = "system:v1",
            KeyVersion = 1,
            AdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            CreatedAt = new System.DateTime(639114135398800440L, System.DateTimeKind.Utc),
            UpdatedAt = new System.DateTime(639114135398800440L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareTarget>().HasData(new
        {
            Id = System.Guid.Parse("0f2cd939-b5d8-42f9-98b9-9d44305ad6dd"),
            ShareGroupId = System.Guid.Parse("c2ed4793-f258-425a-bcf1-f9b24335982b"),
            KeyVersion = 1,
            MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            WrappedContentKey = System.Convert.FromBase64String("xal+GzH5VXqy+smlW0u3t7LaxGsRm9sOXSrJ6lC1Rglc2djNk/kj59qzLXdI1LP2t7k9skqnvkNtYJqg"),
            Role = SyncRole.Owner,
            GrantedByContactId = System.Guid.Parse("ba68902f-58a8-4c9a-b45e-d4123b50caf9"),
            UpdatedAt = new System.DateTime(639114135398800440L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("ac5489bb-628e-4eb5-a917-0fc511ecaabd"),
            ClientGuid = "84b3f377-7ece-449e-b0cf-2eb279f3d3d3",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("ba68902f-58a8-4c9a-b45e-d4123b50caf9")
        });
    }
}