// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context CryptoTestContext --namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync --output SqliteWasmBlazor.TestApp/TestInfrastructure/CryptoSync/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync;

public partial class CryptoTestContext
{
    /// <summary>
    /// Seeds the admin bootstrap data (TrustedContact, ShareGroup, ShareTarget, DeviceSettings).
    /// Call from <see cref="OnModelCreating"/> after <c>base.OnModelCreating</c> and <c>ConfigureCryptoTables</c>.
    /// </summary>
    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("c1513386-8156-4e65-83cb-e1482037243c"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            IsTrusted = true,
            UpdatedAt = new System.DateTime(639114132547428060L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(new
        {
            Id = System.Guid.Parse("d5bf0a22-4f49-466c-8120-93280025233a"),
            GroupContext = "system:v1",
            KeyVersion = 1,
            AdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            CreatedAt = new System.DateTime(639114132547428060L, System.DateTimeKind.Utc),
            UpdatedAt = new System.DateTime(639114132547428060L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareTarget>().HasData(new
        {
            Id = System.Guid.Parse("b94a9ff7-c700-427a-9be4-a697a9892b06"),
            ShareGroupId = System.Guid.Parse("d5bf0a22-4f49-466c-8120-93280025233a"),
            KeyVersion = 1,
            MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            WrappedContentKey = System.Convert.FromBase64String("Q3KZd8aADkJDjlHBU2vJck9NKmUTSJYtjpp9u68dlwZBA2bH0AFeHs3YwtMCZ85q+m1xYntElfkCdRXo"),
            Role = SyncRole.Owner,
            GrantedByContactId = System.Guid.Parse("c1513386-8156-4e65-83cb-e1482037243c"),
            UpdatedAt = new System.DateTime(639114132547428060L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("663bf559-cc9f-42da-aa14-cf0958f45753"),
            ClientGuid = "b215dc1d-ce3b-43bb-8755-d7b8f68ec8d6",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("c1513386-8156-4e65-83cb-e1482037243c")
        });
    }
}