// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context CryptoTestContext --namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync --output ../samples/SqliteWasmBlazor.TestApp/TestInfrastructure/CryptoSync/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync;

public partial class CryptoTestContext
{
    /// <summary>
    /// Admin X25519 private key — for test key derivation. DO NOT use in production.
    /// Static-initializer byte[] (P21 — secret key material exposed to consumers
    /// as bytes, not <see cref="string"/>). The Base64 string literal in this
    /// file's source remains in the compiled assembly metadata; the residual
    /// is acknowledged at codegen layer and out of P21 runtime-API scope.
    /// </summary>
    public static readonly byte[] AdminX25519PrivateKey = System.Convert.FromBase64String("6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=");

    /// <summary>
    /// Admin Ed25519 private key — for test signing. DO NOT use in production.
    /// See <see cref="AdminX25519PrivateKey"/> for the byte[] shape rationale.
    /// </summary>
    public static readonly byte[] AdminEd25519PrivateKey = System.Convert.FromBase64String("0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=");

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("079ba731-4689-446a-a9c1-42cfa92037ec"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            UpdatedAt = new System.DateTime(639141006275261950L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.PUBLIC,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("9801d406-86ae-4892-8a2d-ff4e305b1fda"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639141006275261950L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639141006275261950L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("7b1169bb-82c0-447c-bbf8-272ffa0f0bd3"),
                GroupContext = "self-079ba7314689446aa9c142cfa92037ec:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639141006275261950L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639141006275261950L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("989fe1cc-548b-4891-bf3f-318e334498ab"),
                ShareGroupId = System.Guid.Parse("9801d406-86ae-4892-8a2d-ff4e305b1fda"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("fV8dnPzkqpMDZTGBw/RCyV97/vDlvx6Q3CWaR2AjWfZrTJ4bopJQsmsbrRFIfHA/Dzq3EudOMyP+m5ZA"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("ryoLwPSgB3y/47bNfJ3NlCAdxee9AohC51Bz8by52yKhZdVs8ORXhiK+plBd7jyhZjKfmkoapDr4Y+GcdHlYBg=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("079ba731-4689-446a-a9c1-42cfa92037ec"),
                UpdatedAt = new System.DateTime(639141006275261950L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("e19d0c8f-9663-4b30-9e9c-f09c01b9dc20"),
                ShareGroupId = System.Guid.Parse("7b1169bb-82c0-447c-bbf8-272ffa0f0bd3"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("T/2lVA3di3Uhx/qT6CyKKXNAgGS7gMy31ndDnECPSeiz4yhPp529v8lfIXE1s4G5GB77Q6Q8stTBOTcA"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("RK2/OMkFBz3UbXr7b9ZD8SAvdrN3TfZtdP2d6HjWQRX35S4NOjo/YwFVCe4C1kjwdJXUvKd2QfkjMa/kcJaSBw=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("079ba731-4689-446a-a9c1-42cfa92037ec"),
                UpdatedAt = new System.DateTime(639141006275261950L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("1967f324-3bfc-4224-be2d-cea4a0c105a0"),
            ClientGuid = "329b458e-a159-4d1e-8820-0ea5547acacb",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("079ba731-4689-446a-a9c1-42cfa92037ec"),
            OwnContactId = System.Guid.Parse("079ba731-4689-446a-a9c1-42cfa92037ec")
        });

        modelBuilder.Entity<PermissionTableSignature>().HasData(new
        {
            Id = System.Guid.Parse("ece64655-8999-3ed3-a68d-25b617087d86"),
            PermissionHash = System.Convert.FromBase64String("+ECaUtErN+Oer2R+WXqF8T/m/XycewqFjt0X6r1F5Nk="),
            AdminSignature = System.Convert.FromBase64String("r44FQMFe6KRG3ow662O0mmgJejCxrXIPqu63S3ZYTy1MIQicNrrXGj1UUJPXg9QgSqZmep01KL9SWkD7BLX/Dg=="),
            AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA="
        });
    }
}